id: P211421A7
initial_creation_type: input
source_metadata:
  title: Kurukullā Series
  language: en
  description: 'Texts related to Kurukullā (rig byed ma)—also known to Tibetans as
    Kurukulle—a deity of the Lotus family associated with the activity of magnetization
    or enchantment and one of the twenty-one Tārā emanations:'
  volume:
    65178bc342574ac196a5c73a4435b608:
      title: Guru Yoga Focusing upon Noble Kurukullā
      parent: Guru Yoga
    95caaaf71ec347e4b6017a267c28ac4a:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Sādhanas
    84d7b68e5b794bbeb4f9aa5e405b9583:
      title: A Sādhana of Kurukullā
      parent: Sādhanas
    ca274f13955046b08b4518f9864bcbba:
      title: Short Sang Offering to Kurukullā
      parent: Sang Offering
    8a696b3897444ecf814b1b443d4315d4:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Sang Offering
    daed3050bb744f3ca12989dba85669a6:
      title: Short Torma Offering to Kurukullā
      parent: Torma Offering
    27bcc2e05c6a432a96e25e7b1b4b235d:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Tsok
created_at: '2022-03-01T04:06:17.442624'
last_modified_at: '2022-03-01T04:06:17.442630'
